name: facilepadigitale
favicon: null
layout_spectrum: 0.5470527089200914
typography_spectrum: 0.20251043373718858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce2b37'
    - '#009246'
    - '#454545'
    - '#b1b1b1'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.276513384655118
  rhythmicContrast: 0.47571642394177616
purpose: []
